/**
 * module-map-mirror-safety.test.ts — lock-in for the R125+148 architect finding
 * on the auto-generated module map (docs/MODULE_MAP.md).
 *
 * The map is generated by scripts/refresh-module-map.ts and, for the public
 * mirror, MUST be regenerated from the SANITIZED mirror tree at stage [3.7/5]
 * of scripts/build-public-mirror.sh (after exclusions + sed scrubs, BEFORE the
 * stage-4 leak scan). Generating it from the private tree leaks excluded
 * module names and private header-comment text into a public document.
 *
 * What this pins:
 *  1. LEAK VECTOR IS REAL: a staged tree containing a private-comment module
 *     produces a map that includes that module's path and comment text.
 *  2. SANITIZED-TREE GENERATION IS SAFE: the same staged tree WITHOUT the
 *     private module produces a map with zero trace of it — and generation
 *     OVERWRITES any pre-existing (private-tree) map in the target.
 *  3. FAIL-CLOSED WIRING: build-public-mirror.sh stage 3.7 runs the generator
 *     with --root "$DST", sits between the scrub stage and the [4/5] leak
 *     scan, and rm -f's the map on both failure branches (generator failure,
 *     npx missing) rather than shipping a private-tree copy.
 *  4. The generator hard-fails (exit 2) on a missing --root dir.
 */

import test from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

const GENERATOR = "scripts/refresh-module-map.ts";
const MIRROR_SH = "scripts/build-public-mirror.sh";
const PRIVATE_COMMENT = "discovers clips from Bobs private Drive folder ZZPRIVATEZZ";
const PRIVATE_FILE = "server/zz-private-ops.ts";

function runGenerator(root: string) {
  // Spawn from the workspace cwd so tsx module resolution works
  // (tsx-probe-outside-workspace gotcha); --root only redirects the scan.
  return spawnSync("npx", ["--no-install", "tsx", GENERATOR, "--root", root], {
    encoding: "utf8",
    timeout: 120_000,
  });
}

function stageTree(withPrivate: boolean): string {
  const root = mkdtempSync(join(tmpdir(), "mm-safety-"));
  mkdirSync(join(root, "server"), { recursive: true });
  mkdirSync(join(root, "docs"), { recursive: true });
  writeFileSync(
    join(root, "server", "good.ts"),
    "// public helper module, safe to ship\nexport const ok = 1;\n",
  );
  if (withPrivate) {
    writeFileSync(
      join(root, PRIVATE_FILE),
      `// ${PRIVATE_COMMENT}\nexport const secretish = 2;\n`,
    );
  }
  return root;
}

test("leak vector is real: private module + comment appear when present in the scanned tree", () => {
  const root = stageTree(true);
  try {
    const res = runGenerator(root);
    assert.equal(res.status, 0, `generator failed: ${res.stderr}`);
    const map = readFileSync(join(root, "docs", "MODULE_MAP.md"), "utf8");
    assert.ok(map.includes("zz-private-ops.ts"), "expected private module in map (leak vector demo)");
    assert.ok(map.includes("ZZPRIVATEZZ"), "expected private comment text in map (leak vector demo)");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("sanitized tree yields a clean map AND overwrites a stale private-tree copy", () => {
  const root = stageTree(false);
  try {
    // Simulate a stale private-tree map already sitting in the target.
    writeFileSync(
      join(root, "docs", "MODULE_MAP.md"),
      `# stale private map\n${PRIVATE_FILE} — ${PRIVATE_COMMENT}\n`,
    );
    const res = runGenerator(root);
    assert.equal(res.status, 0, `generator failed: ${res.stderr}`);
    const map = readFileSync(join(root, "docs", "MODULE_MAP.md"), "utf8");
    assert.ok(map.includes("good.ts"), "included module must appear");
    assert.ok(!map.includes("zz-private-ops"), "excluded module path must not appear");
    assert.ok(!map.includes("ZZPRIVATEZZ"), "private comment text must not appear");
    assert.ok(!map.includes("stale private map"), "stale private-tree copy must be overwritten");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("generator fails closed (exit 2) on a missing --root", () => {
  const res = runGenerator("/nonexistent-mm-safety-dir");
  assert.equal(res.status, 2, `expected exit 2, got ${res.status}: ${res.stdout}${res.stderr}`);
});

test("mirror build wiring: stage 3.7 generates from $DST after scrubs, before leak scan, rm -f on failure", () => {
  assert.ok(existsSync(MIRROR_SH), `${MIRROR_SH} missing`);
  const sh = readFileSync(MIRROR_SH, "utf8");

  const scrubIdx = sh.indexOf("[3/5] running sed scrubs");
  const stageIdx = sh.indexOf("[3.7/5] regenerating docs/MODULE_MAP.md");
  const verifyIdx = sh.indexOf("[4/5] verification");
  assert.ok(scrubIdx !== -1 && stageIdx !== -1 && verifyIdx !== -1, "expected stage markers missing");
  assert.ok(scrubIdx < stageIdx && stageIdx < verifyIdx,
    "stage 3.7 must run AFTER sed scrubs and BEFORE the [4/5] leak scan");

  const block = sh.slice(stageIdx, verifyIdx);
  assert.ok(/refresh-module-map\.ts --root "\$DST"/.test(block),
    "stage 3.7 must generate with --root \"$DST\" (the sanitized mirror tree)");
  const rmCount = (block.match(/rm -f "\$DST\/docs\/MODULE_MAP\.md"/g) || []).length;
  assert.ok(rmCount >= 2,
    `both failure branches (generator fail + npx missing) must rm -f the map; found ${rmCount}`);
  // Every actual INVOCATION (tsx …) must carry --root; prose mentions in
  // echo/warning lines are fine.
  const invocations = block.split("\n").filter((l) => /tsx\s+\S*refresh-module-map\.ts/.test(l));
  assert.ok(invocations.length >= 1, "expected at least one generator invocation in stage 3.7");
  for (const inv of invocations) {
    assert.ok(inv.includes('--root "$DST"'),
      `root-less (private-tree) invocation not allowed: ${inv.trim()}`);
  }
});
