/**
 * Source-union parity — tools-layer-split slice S1 regression guard.
 * Contract: data/feature-contracts/tools-layer-split/
 *
 * Proves the shared static parser (scripts/lib/tool-source-files.ts) that every
 * text-parsing consumer now uses:
 *   1. always includes server/tools.ts FIRST (legacy monolith / facade),
 *   2. finds the full registered toolset (floor guard — never shrinks),
 *   3. finds ZERO duplicate tool names across source files — a duplicate means
 *      a definition was copied into a domain file without being removed from
 *      the monolith (a half-finished migration slice).
 *
 * Deliberately DB-free and app-graph-free: importing server/tools.ts pulls the
 * whole app graph (and node:test + a live pg pool hangs the runner), so this
 * test is pure static text analysis, same as the consumers it guards.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import * as fs from "node:fs";
import * as path from "node:path";
import {
  getToolSourceFiles,
  readToolSourcesConcatenated,
  extractToolNamesStatic,
} from "../../scripts/lib/tool-source-files";

// Canonical inventory baseline: generated by `npx tsx scripts/list-tools.ts`
// (runtime TOOL_DEFINITIONS) at slice-gate time and committed alongside the
// contract. The union parser must find EXACTLY this set — not a floor.
// Regenerate deliberately when tools are added/removed:
//   npx tsx scripts/list-tools.ts | grep -oE '^[a-z][a-z0-9_]*' | sort \
//     > data/feature-contracts/tools-layer-split/tool-inventory-baseline.txt
const BASELINE_PATH = path.join(
  process.cwd(),
  "data/feature-contracts/tools-layer-split/tool-inventory-baseline.txt",
);
function readBaselineNames(): string[] {
  return fs
    .readFileSync(BASELINE_PATH, "utf8")
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean);
}

test("server/tools.ts is present and first in the source union", () => {
  const files = getToolSourceFiles();
  assert.ok(files.length >= 1, "no tool source files found");
  assert.equal(path.relative(process.cwd(), files[0]), path.join("server", "tools.ts"));
  for (const f of files.slice(1)) {
    const rel = path.relative(process.cwd(), f);
    assert.ok(
      rel.startsWith(path.join("server", "tools", "domains") + path.sep),
      `unexpected non-domain file in union: ${rel}`,
    );
    assert.ok(!rel.endsWith(".test.ts"), `test file leaked into union: ${rel}`);
  }
});

test("union parser finds EXACTLY the canonical inventory (set equality, both directions)", () => {
  const { names } = extractToolNamesStatic();
  for (const n of names) {
    assert.match(n, /^[a-z][a-z0-9_]*$/, `malformed tool name extracted: ${n}`);
  }
  const parsed = new Set(names);
  const baseline = new Set(readBaselineNames());
  assert.ok(baseline.size >= 394, `baseline file suspiciously small (${baseline.size}) — regenerate it`);

  const missing = [...baseline].filter((n) => !parsed.has(n));
  const extra = [...parsed].filter((n) => !baseline.has(n));
  assert.deepEqual(
    missing,
    [],
    `union parser is BLIND to ${missing.length} canonical tool(s): ${missing.slice(0, 10).join(", ")} — a parsing consumer (smoke-test/wiring-audit/docs) would silently drop them`,
  );
  assert.deepEqual(
    extra,
    [],
    `union parser extracted ${extra.length} name(s) NOT in the canonical inventory: ${extra.slice(0, 10).join(", ")} — false-positive extraction OR the baseline needs a deliberate regeneration (see header comment)`,
  );
});

test("no tool name is defined in more than one source file", () => {
  const { duplicates } = extractToolNamesStatic();
  assert.deepEqual(
    duplicates,
    [],
    `duplicate tool definitions across source files (half-finished migration slice?): ${duplicates.join(", ")}`,
  );
});

test("concatenated read contains every source file's marker", () => {
  const text = readToolSourcesConcatenated();
  for (const f of getToolSourceFiles()) {
    const rel = path.relative(process.cwd(), f);
    assert.ok(text.includes(`// ===== FILE: ${rel} =====`), `missing marker for ${rel}`);
  }
});
