// SkillOpt-style validation-gated skill optimizer.
//
// Concept imported from Microsoft's SkillOpt (arXiv:2605.23904, MIT). The skill
// DOCUMENT is treated as the trainable state of a frozen agent: an optimizer model
// proposes ONE bounded add/delete/replace edit per epoch; a candidate edit is
// accepted ONLY when it STRICTLY improves a held-out validation score; rejected
// edits go into a buffer so the optimizer never re-proposes the same losing edit.
// The output is just an improved skill document — zero inference-time cost at
// deployment (the doc is prepended to the unchanged target model).
//
// Faithful to VisionClaw's existing infra: optimizer/target/grader models go
// through server/providers.ts (cost-tracked), and the loop is fully injectable so
// the pure logic can be unit-tested with no real LLM calls. Providers are imported
// LAZILY inside the default LLM functions so this module is import-safe for tests.

import {
  type PriorCollapseLike,
  renderSkillEditText,
  buildPerturbationDirective,
  safeCollapseCheck,
  safeCollapseRemember,
} from "./lib/prior-collapse";

export interface EvalCase {
  /** The task/prompt handed to the target (frozen) model. */
  input: string;
  /** Optional gold answer used by the grader. */
  reference?: string;
  /** Optional free-text grading rubric. */
  rubric?: string;
}

export type EditOp = "add" | "delete" | "replace";

export interface SkillEdit {
  op: EditOp;
  /** For delete/replace: substring to locate. For add: optional anchor to insert after. */
  target?: string;
  /** For add: text appended/inserted. For replace: replacement text. */
  text?: string;
  rationale?: string;
}

export interface ScoredRollout {
  input: string;
  output: string;
  /** 0..1 */
  score: number;
  notes?: string;
}

export interface OptimizeConfig {
  epochs?: number;
  /** Train cases sampled per epoch to surface failures for the optimizer. */
  minibatchSize?: number;
  /** Fraction of cases held out for the accept/reject gate. */
  valSplit?: number;
  optimizerModel?: string;
  targetModel?: string;
  graderModel?: string;
  /** Strict-improvement epsilon: accept only if candidateScore > bestScore + this. */
  minImprovement?: number;
  /**
   * Shrink guard (ACE brevity-bias defense, arXiv:2510.04618 "context
   * collapse"): a candidate that would otherwise be accepted is REJECTED when
   * its trimmed length has fallen below (1 - shrinkGuardFraction) of the
   * ORIGINAL seed doc's trimmed length — unless it beats the current best by
   * at least shrinkStrongEps (a "strong" gain that earns the compression).
   * Measured against the seed, not the parent, so gradual collapse across
   * several accepted edits cannot compound under the radar. Fraction is in
   * (0,1); default 0.4 (i.e. reject once the doc is under 60% of seed size).
   */
  shrinkGuardFraction?: number;
  /** Score margin (0..1 scale) that lets a big shrink through anyway. Default 0.05. */
  shrinkStrongEps?: number;
  tenantId?: number;
  seed?: number;
  /** Injection seam (tests / custom harnesses): score one rollout for a doc. */
  rolloutFn?: (skillDoc: string, c: EvalCase) => Promise<ScoredRollout>;
  /** Injection seam: propose one bounded edit (or null to skip the epoch). */
  proposeFn?: (
    skillDoc: string,
    failures: ScoredRollout[],
    rejected: string[],
  ) => Promise<SkillEdit | null>;
  /**
   * Prior-collapse detector (Bilevel Autoresearch borrow, arXiv:2603.23420):
   * when the proposer emits an edit SEMANTICALLY near-identical to one already
   * rejected (cosmetic rewording the exact-signature buffer can't see), skip
   * the val-scoring spend and inject a perturbation directive into the next
   * propose call. OPT-IN: production entrypoints pass a PriorCollapseTracker;
   * when absent (all hermetic tests) the loop behaves exactly as before.
   */
  collapseTracker?: PriorCollapseLike;
  /**
   * Crossover operator (Frontis-MA1/OpenMLE borrow, arXiv:2607.28568): after
   * the hill-climb loop, when the run produced TWO distinct candidates that
   * both beat the baseline (the accepted best + the highest-scoring rejected
   * runner-up), one extra child candidate is generated by merging them and is
   * accepted ONLY on strict val-improvement over the current best — the same
   * gate every other candidate faces. OPT-IN (default off); every failure
   * path fails OPEN (result unchanged, reason recorded).
   */
  crossover?: boolean;
  /** Injection seam: merge two parent docs into a child (or null to skip). */
  crossoverFn?: (docA: string, docB: string) => Promise<string | null>;
  /**
   * AIDE-style branch-on-stall (WecoAI aideml borrow, arXiv:2502.13138): the
   * hill-climb keeps a small pool of REJECTED candidates that still beat the
   * baseline (alternative lineages a linear climb throws away). When the climb
   * stalls for `stallEpochs` consecutive epochs, the next proposal branches
   * from a pool member instead of the current best — AIDE's escape from a
   * local optimum. Acceptance is UNCHANGED: a branched candidate must still
   * strictly beat the global best on the held-out val set. OPT-IN (default
   * off); with the flag off or the pool empty, behavior is byte-identical.
   */
  branchOnStall?: boolean;
  /** Consecutive non-accepted epochs before branching kicks in (default 2). */
  stallEpochs?: number;
  /** Max rejected-but-baseline-beating parents retained (default 3). */
  parentPoolSize?: number;
}

export interface EpochRecord {
  epoch: number;
  candidateScore: number | null;
  bestScore: number;
  accepted: boolean;
  edit: SkillEdit | null;
  reason: string;
  /** Max cosine vs rejected priors when the prior-collapse check ran (reason "prior-collapse"). */
  similarity?: number | null;
  /** True when this epoch's proposal branched from a pool parent, not the current best. */
  branched?: boolean;
}

export interface OptimizeResult {
  baselineScore: number;
  bestScore: number;
  bestSkill: string;
  improved: boolean;
  epochs: EpochRecord[];
  acceptedEdits: SkillEdit[];
  rejectedCount: number;
  /** True when the post-loop crossover child became the final bestSkill. */
  crossoverApplied?: boolean;
}

// ─── Pure helpers (deterministic, no I/O) ──────────────────────────────────

/** Small deterministic PRNG so train/val split + minibatch sampling are reproducible. */
export function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function normalize(s: string | undefined): string {
  return (s ?? "").replace(/\s+/g, " ").trim().toLowerCase();
}

/** Stable signature for the rejected-edit buffer (semantically-equal edits collapse). */
export function editSignature(edit: SkillEdit): string {
  return `${edit.op}::${normalize(edit.target)}::${normalize(edit.text)}`;
}

/** Apply one bounded edit to a skill doc. Returns the doc UNCHANGED on a no-op. */
export function applyEdit(doc: string, edit: SkillEdit): string {
  const text = edit.text ?? "";
  const target = edit.target ?? "";
  switch (edit.op) {
    case "add": {
      if (!text.trim()) return doc;
      if (target && doc.includes(target)) {
        const idx = doc.indexOf(target) + target.length;
        return doc.slice(0, idx) + "\n" + text + doc.slice(idx);
      }
      return doc.endsWith("\n") ? doc + text : doc + "\n" + text;
    }
    case "delete": {
      if (!target || !doc.includes(target)) return doc;
      return doc.replace(target, "");
    }
    case "replace": {
      if (!target || !doc.includes(target) || text === target) return doc;
      return doc.replace(target, text);
    }
    default:
      return doc;
  }
}

/**
 * True when the candidate doc has shrunk past the guard threshold AND its
 * score gain is not strong enough to justify the compression. Fail-closed on
 * the shrink side (a collapsed doc is rejected), fail-open on degenerate
 * inputs (seedLen <= 0 disables the guard rather than blocking everything).
 */
export function violatesShrinkGuard(
  seedLen: number,
  candidateLen: number,
  candidateScore: number,
  bestScore: number,
  opts: { fraction: number; strongEps: number },
): boolean {
  if (!Number.isFinite(seedLen) || seedLen <= 0) return false;
  const floor = seedLen * (1 - Math.min(0.99, Math.max(0.01, opts.fraction)));
  if (candidateLen >= floor) return false;
  return !(candidateScore > bestScore + Math.max(0, opts.strongEps));
}

export function isStrictImprovement(candidate: number, best: number, eps = 0): boolean {
  // eps is clamped to >= 0 so a caller can never weaken the gate below "strictly
  // greater than best" (e.g. a negative epsilon that would accept worse candidates).
  return candidate > best + Math.max(0, eps);
}

function reqInt(v: number | undefined, def: number, min: number, name: string): number {
  if (v === undefined) return def;
  if (!Number.isFinite(v) || v < min) {
    throw new Error(`optimizeSkill: ${name} must be a finite number >= ${min} (got ${v}).`);
  }
  return Math.floor(v);
}

function reqFrac(v: number | undefined, def: number, name: string): number {
  if (v === undefined) return def;
  if (!Number.isFinite(v) || v <= 0 || v >= 1) {
    throw new Error(`optimizeSkill: ${name} must be a finite number in (0,1) (got ${v}).`);
  }
  return v;
}

export function aggregate(scored: ScoredRollout[]): number {
  if (scored.length === 0) return 0;
  return scored.reduce((s, r) => s + r.score, 0) / scored.length;
}

/** Deterministic shuffle + train/val split. */
export function splitTrainVal(
  cases: EvalCase[],
  valSplit: number,
  seed: number,
): { train: EvalCase[]; val: EvalCase[] } {
  const rng = mulberry32(seed);
  const idx = cases.map((_, i) => i);
  for (let i = idx.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [idx[i], idx[j]] = [idx[j], idx[i]];
  }
  const shuffled = idx.map((i) => cases[i]);
  const clamped = Math.min(0.9, Math.max(0.1, valSplit));
  let nVal = Math.round(shuffled.length * clamped);
  nVal = Math.min(shuffled.length - 1, Math.max(1, nVal));
  return { val: shuffled.slice(0, nVal), train: shuffled.slice(nVal) };
}

function sampleMinibatch(cases: EvalCase[], n: number, rng: () => number): EvalCase[] {
  if (cases.length <= n) return cases.slice();
  const pool = cases.slice();
  const out: EvalCase[] = [];
  for (let k = 0; k < n && pool.length; k++) {
    out.push(pool.splice(Math.floor(rng() * pool.length), 1)[0]);
  }
  return out;
}

function extractJson(raw: string): any | null {
  if (!raw) return null;
  const fenced = raw.match(/```(?:json)?\s*([\s\S]*?)```/i);
  const body = fenced ? fenced[1] : raw;
  const start = body.indexOf("{");
  const end = body.lastIndexOf("}");
  if (start === -1 || end === -1 || end <= start) return null;
  try {
    return JSON.parse(body.slice(start, end + 1));
  } catch {
    return null;
  }
}

// ─── Default LLM-backed harness (providers imported lazily) ─────────────────

/**
 * The holistic scalar judge: one opaque 0..1 score for a candidate answer. This
 * is the CURRENT reward function. Exported so the BINEVAL A/B (server/lib/
 * bineval.ts) can grade the same outputs with the exact same logic — the A/B
 * compares this judge against the binary-question decomposition.
 */
export async function holisticGrade(
  task: string,
  output: string,
  rubric: string | undefined,
  reference: string | undefined,
  cfg: { graderModel: string },
): Promise<{ score: number; notes?: string }> {
  const { replitOpenai } = await import("./providers");
  const rubricBlock = rubric
    ? `Rubric:\n${rubric}`
    : "Rubric: correctness, completeness, and concision.";
  const ref = reference ? `\nReference answer:\n${reference}` : "";
  const gradePrompt =
    `Grade the candidate answer from 0.0 to 1.0.\n\nTask:\n${task}\n\n${rubricBlock}${ref}\n\n` +
    `Candidate answer:\n${output}\n\nReturn ONLY JSON: {"score": <0..1>, "notes": "<short>"}`;
  const grade = await replitOpenai.chat.completions.create({
    model: cfg.graderModel,
    messages: [{ role: "user", content: gradePrompt }],
  });
  const parsed = extractJson(grade.choices?.[0]?.message?.content ?? "");
  let score = typeof parsed?.score === "number" ? parsed.score : 0;
  score = Math.max(0, Math.min(1, score));
  return { score, notes: parsed?.notes };
}

async function defaultRollout(
  skillDoc: string,
  c: EvalCase,
  cfg: { targetModel: string; graderModel: string; tenantId?: number },
): Promise<ScoredRollout> {
  const { getClientForModel } = await import("./providers");
  const { client, actualModelId } = await getClientForModel(cfg.targetModel, cfg.tenantId);
  const comp = await client.chat.completions.create({
    model: actualModelId,
    messages: [
      { role: "system", content: skillDoc },
      { role: "user", content: c.input },
    ],
  });
  const output = comp.choices?.[0]?.message?.content?.trim() ?? "";

  const { score, notes } = await holisticGrade(c.input, output, c.rubric, c.reference, {
    graderModel: cfg.graderModel,
  });
  return { input: c.input, output, score, notes };
}

async function defaultPropose(
  skillDoc: string,
  failures: ScoredRollout[],
  rejected: string[],
  cfg: { optimizerModel: string; tenantId?: number },
): Promise<SkillEdit | null> {
  const { getClientForModel } = await import("./providers");
  const { client, actualModelId } = await getClientForModel(cfg.optimizerModel, cfg.tenantId);
  const failBlock = failures
    .slice(0, 4)
    .map(
      (f, i) =>
        `#${i + 1} (score ${f.score.toFixed(2)})\nINPUT: ${f.input}\nOUTPUT: ${f.output}` +
        (f.notes ? `\nGRADER: ${f.notes}` : ""),
    )
    .join("\n\n");
  const rejBlock = rejected.length
    ? `\n\nDo NOT propose any of these previously-rejected edits again:\n- ${rejected.join("\n- ")}`
    : "";
  const prompt =
    `You are optimizing a SKILL DOCUMENT that is prepended to a frozen LLM. Improve it so the ` +
    `failing cases below would score higher, WITHOUT overfitting. Propose exactly ONE small, ` +
    `bounded edit.\n\nCURRENT SKILL DOCUMENT:\n"""\n${skillDoc}\n"""\n\nFAILING ROLLOUTS:\n${failBlock}${rejBlock}\n\n` +
    `Return ONLY JSON: {"op":"add"|"delete"|"replace","target":"<exact substring for delete/replace, or anchor for add, may be empty>","text":"<new/replacement text, empty for delete>","rationale":"<why>"}`;
  const comp = await client.chat.completions.create({
    model: actualModelId,
    messages: [{ role: "user", content: prompt }],
  });
  const parsed = extractJson(comp.choices?.[0]?.message?.content ?? "");
  if (!parsed || (parsed.op !== "add" && parsed.op !== "delete" && parsed.op !== "replace")) {
    return null;
  }
  return {
    op: parsed.op,
    target: typeof parsed.target === "string" ? parsed.target : "",
    text: typeof parsed.text === "string" ? parsed.text : "",
    rationale: typeof parsed.rationale === "string" ? parsed.rationale : undefined,
  };
}

/**
 * Default LLM-backed crossover: merge two improving skill-doc variants into
 * one child doc. Prompt-level only — no weights, no RL (the paper's training
 * half is inapplicable on API models; this borrows only the operator).
 */
async function defaultCrossover(
  docA: string,
  docB: string,
  cfg: { optimizerModel: string; tenantId?: number },
): Promise<string | null> {
  const { getClientForModel } = await import("./providers");
  const { client, actualModelId } = await getClientForModel(cfg.optimizerModel, cfg.tenantId);
  const prompt =
    `Two variants of the same SKILL DOCUMENT each improved a frozen LLM's eval score. ` +
    `Merge them into ONE child document that keeps the strengths of both. Do not add new ` +
    `instructions absent from both parents; do not drop shared content; keep it concise.\n\n` +
    `PARENT A (current best):\n"""\n${docA}\n"""\n\nPARENT B (runner-up):\n"""\n${docB}\n"""\n\n` +
    `Return ONLY the merged skill document text — no commentary, no code fences.`;
  const comp = await client.chat.completions.create({
    model: actualModelId,
    messages: [{ role: "user", content: prompt }],
  });
  let out = comp.choices?.[0]?.message?.content?.trim() ?? "";
  // Strip an accidental fence wrapper.
  const fenced = out.match(/^```(?:\w+)?\s*([\s\S]*?)```$/);
  if (fenced) out = fenced[1].trim();
  return out || null;
}

// ─── Main loop ──────────────────────────────────────────────────────────────

export async function optimizeSkill(
  skillDoc: string,
  cases: EvalCase[],
  config: OptimizeConfig = {},
): Promise<OptimizeResult> {
  const epochs = reqInt(config.epochs, 6, 1, "epochs");
  const minibatchSize = reqInt(config.minibatchSize, 4, 1, "minibatchSize");
  const valSplit = reqFrac(config.valSplit, 0.4, "valSplit");
  const eps = Math.max(0, Number.isFinite(config.minImprovement as number) ? (config.minImprovement as number) : 0);
  const shrinkGuardFraction = reqFrac(config.shrinkGuardFraction, 0.4, "shrinkGuardFraction");
  const shrinkStrongEps = Math.max(
    0,
    Number.isFinite(config.shrinkStrongEps as number) ? (config.shrinkStrongEps as number) : 0.05,
  );
  const seed = Number.isFinite(config.seed as number) ? (config.seed as number) : 1234;
  const optimizerModel = config.optimizerModel ?? "gpt-5.6-sol";
  const targetModel = config.targetModel ?? "gpt-5-mini";
  const graderModel = config.graderModel ?? "gpt-5-mini";

  if (cases.length < 2) {
    throw new Error("optimizeSkill needs at least 2 eval cases (one train, one validation).");
  }

  const rollout =
    config.rolloutFn ??
    ((doc: string, c: EvalCase) =>
      defaultRollout(doc, c, { targetModel, graderModel, tenantId: config.tenantId }));
  const propose =
    config.proposeFn ??
    ((doc: string, fails: ScoredRollout[], rej: string[]) =>
      defaultPropose(doc, fails, rej, { optimizerModel, tenantId: config.tenantId }));

  const { train, val } = splitTrainVal(cases, valSplit, seed);
  const rng = mulberry32(seed ^ 0x9e3779b9);

  const scoreOn = async (doc: string, set: EvalCase[]): Promise<ScoredRollout[]> =>
    Promise.all(set.map((c) => rollout(doc, c)));

  const baselineScore = aggregate(await scoreOn(skillDoc, val));
  const seedLen = skillDoc.trim().length;

  let bestSkill = skillDoc;
  let bestScore = baselineScore;
  // Parent pool: REJECTED candidates that still beat the baseline — genuine
  // second lineages a linear hill-climb would discard. Feeds BOTH the
  // post-loop crossover (top entry = runner-up parent) and, when
  // branchOnStall is set, the AIDE-style branch-on-stall escape.
  const branchOnStall = config.branchOnStall === true;
  const stallEpochs = reqInt(config.stallEpochs, 2, 1, "stallEpochs");
  const parentPoolSize = reqInt(config.parentPoolSize, 3, 1, "parentPoolSize");
  const parentPool: { doc: string; score: number }[] = [];
  const poolConsider = (doc: string, score: number) => {
    if (!(score > baselineScore) || doc === bestSkill) return;
    if (parentPool.some((p) => p.doc === doc)) return;
    parentPool.push({ doc, score });
    parentPool.sort((a, b) => b.score - a.score);
    if (parentPool.length > parentPoolSize) parentPool.length = parentPoolSize;
  };
  let stall = 0; // consecutive non-accepted epochs
  let branchCursor = 0; // cycles through the pool across branch attempts
  const rejected: string[] = [];
  const rejectedSet = new Set<string>();
  const acceptedEdits: SkillEdit[] = [];
  const records: EpochRecord[] = [];
  // Prior-collapse (arXiv:2603.23420): once a near-dupe of a rejected edit is
  // seen, this directive rides along in the rejected list shown to the
  // proposer until the run ends (perturb, not retry).
  let perturbDirective: string | null = null;

  for (let e = 1; e <= epochs; e++) {
    // AIDE-style parent selection: normally the current best; when the climb
    // has stalled and the pool holds an alternative baseline-beating lineage,
    // branch from a pool member (cycled) to escape the local optimum.
    let parentDoc = bestSkill;
    let branched = false;
    if (branchOnStall && stall >= stallEpochs && parentPool.length > 0) {
      const pick = parentPool[branchCursor % parentPool.length];
      branchCursor++;
      if (pick.doc !== bestSkill) {
        parentDoc = pick.doc;
        branched = true;
      }
    }

    const batch = sampleMinibatch(train, minibatchSize, rng);
    const rollouts = await scoreOn(parentDoc, batch);
    const failures = rollouts.slice().sort((a, b) => a.score - b.score);

    const edit = await propose(
      parentDoc,
      failures,
      perturbDirective ? [...rejected, perturbDirective] : rejected,
    );
    if (!edit) {
      records.push({ epoch: e, candidateScore: null, bestScore, accepted: false, edit: null, reason: "no-edit-proposed", ...(branched ? { branched } : {}) });
      stall++;
      continue;
    }

    const sig = editSignature(edit);
    if (rejectedSet.has(sig)) {
      records.push({ epoch: e, candidateScore: null, bestScore, accepted: false, edit, reason: "duplicate-rejected-edit", ...(branched ? { branched } : {}) });
      stall++;
      continue;
    }

    // Semantic near-dupe vs an already-rejected edit → skip the val-scoring
    // spend entirely; a proven-losing idea reworded is still a losing idea.
    // Fail-OPEN: tracker absent / embedding unavailable ⇒ normal path.
    const editText = renderSkillEditText(edit);
    if (config.collapseTracker) {
      const verdict = await safeCollapseCheck(config.collapseTracker, editText);
      if (verdict.collapsed) {
        rejectedSet.add(sig);
        rejected.push(sig);
        perturbDirective = buildPerturbationDirective(verdict.similarity, "skill-edit");
        records.push({
          epoch: e,
          candidateScore: null,
          bestScore,
          accepted: false,
          edit,
          reason: "prior-collapse",
          similarity: verdict.similarity,
          ...(branched ? { branched } : {}),
        });
        stall++;
        continue;
      }
    }

    const candidate = applyEdit(parentDoc, edit);
    if (candidate === parentDoc) {
      rejectedSet.add(sig);
      rejected.push(sig);
      await safeCollapseRemember(config.collapseTracker, editText);
      records.push({ epoch: e, candidateScore: null, bestScore, accepted: false, edit, reason: "no-op-edit", ...(branched ? { branched } : {}) });
      stall++;
      continue;
    }

    const candidateScore = aggregate(await scoreOn(candidate, val));
    if (isStrictImprovement(candidateScore, bestScore, eps)) {
      // ACE shrink guard: an "improvement" that collapses the doc's substance
      // is rejected unless the gain is strong enough to earn the compression.
      if (
        violatesShrinkGuard(seedLen, candidate.trim().length, candidateScore, bestScore, {
          fraction: shrinkGuardFraction,
          strongEps: shrinkStrongEps,
        })
      ) {
        rejectedSet.add(sig);
        rejected.push(sig);
        await safeCollapseRemember(config.collapseTracker, editText);
        stall++;
        records.push({ epoch: e, candidateScore, bestScore, accepted: false, edit, reason: "shrink-guard", ...(branched ? { branched } : {}) });
        continue;
      }
      bestScore = candidateScore;
      bestSkill = candidate;
      acceptedEdits.push(edit);
      stall = 0;
      records.push({ epoch: e, candidateScore, bestScore, accepted: true, edit, reason: branched ? "strict-improvement-branch" : "strict-improvement" });
    } else {
      rejectedSet.add(sig);
      rejected.push(sig);
      await safeCollapseRemember(config.collapseTracker, editText);
      stall++;
      records.push({ epoch: e, candidateScore, bestScore, accepted: false, edit, reason: "no-improvement", ...(branched ? { branched } : {}) });
      poolConsider(candidate, candidateScore);
    }
  }

  // ── Crossover step (Frontis-MA1/OpenMLE, arXiv:2607.28568) ────────────────
  // Runs at most ONCE, only when two distinct baseline-beating parents exist
  // (accepted best + rejected runner-up). The child faces the identical
  // strict-improvement gate; every failure path fails OPEN.
  let crossoverApplied = false;
  const runnerUpDoc = parentPool.find((p) => p.doc !== bestSkill)?.doc ?? null;
  if (config.crossover && runnerUpDoc && bestSkill !== skillDoc && runnerUpDoc !== bestSkill) {
    const xEpoch = epochs + 1;
    try {
      const cross =
        config.crossoverFn ??
        ((a: string, b: string) => defaultCrossover(a, b, { optimizerModel, tenantId: config.tenantId }));
      const child = await cross(bestSkill, runnerUpDoc);
      if (!child || !child.trim() || child === bestSkill || child === runnerUpDoc) {
        records.push({ epoch: xEpoch, candidateScore: null, bestScore, accepted: false, edit: null, reason: "crossover-no-child" });
      } else {
        const childScore = aggregate(await scoreOn(child, val));
        if (
          isStrictImprovement(childScore, bestScore, eps) &&
          violatesShrinkGuard(seedLen, child.trim().length, childScore, bestScore, {
            fraction: shrinkGuardFraction,
            strongEps: shrinkStrongEps,
          })
        ) {
          records.push({ epoch: xEpoch, candidateScore: childScore, bestScore, accepted: false, edit: null, reason: "crossover-shrink-guard" });
        } else if (isStrictImprovement(childScore, bestScore, eps)) {
          bestScore = childScore;
          bestSkill = child;
          crossoverApplied = true;
          records.push({ epoch: xEpoch, candidateScore: childScore, bestScore, accepted: true, edit: null, reason: "crossover-improvement" });
        } else {
          records.push({ epoch: xEpoch, candidateScore: childScore, bestScore, accepted: false, edit: null, reason: "crossover-no-improvement" });
        }
      }
    } catch (err) {
      // Fail OPEN: a broken crossover must never cost the run its loop result.
      records.push({ epoch: xEpoch, candidateScore: null, bestScore, accepted: false, edit: null, reason: `crossover-failed: ${(err as Error).message}` });
    }
  }

  return {
    baselineScore,
    bestScore,
    bestSkill,
    improved: bestScore > baselineScore,
    epochs: records,
    acceptedEdits,
    rejectedCount: rejectedSet.size,
    crossoverApplied,
  };
}
