// One-off addendum (task: nightly tenant-isolation audit permanently red, 2026-08-01):
// second campaign pass for the 13 sites the 2026-08-01 09:25 nightly run kept
// (nondeterministic first-pass model surfaced new sites vs the 02:23 run).
// Each disposition was verified by reading the code site. Appends to
// suppressions.json / deferrals.json and to campaign-2026-08-01-snapshot.json.
// Run: npx tsx scripts/lib/generate-triage-entries-2.ts --write
import fs from "node:fs";
import path from "node:path";
import { extractStructuralAnchor, isUsableCodeLine } from "../../server/lib/audit-suppressions";

const DIR = path.join("data", "tenant-isolation-audit");
const WRITE = process.argv.includes("--write");
const TODAY = "2026-08-01";
const VERIFIER = "task-118 audit-recovery campaign 2026-08-01 (pass 2)";

type Dispo = { kind: "suppress"; pattern: string; reason: string } | { kind: "defer"; reason: string; reviewBy: string };
const S = (pattern: string, reason: string): Dispo => ({ kind: "suppress", pattern, reason });
const D = (reason: string, reviewBy = "2026-09-30"): Dispo => ({ kind: "defer", reason, reviewBy });

const DISPOSITIONS: Record<string, Dispo> = {
  "server/agentic-features.ts:599": S("upstream-verified", "the dedupe SELECT is scoped to sequence_id, and the sequence was tenant-verified (WHERE id AND tenant_id) one statement above; enrollment rows only exist under that sequence."),
  "server/build-video-from-brief.ts:714": S("upstream-verified", "tenantId is explicitly threaded into StartVideoJobInput on the adjacent line; downstream project_files writes are gated by assertProjectInTenant."),
  "server/email.ts:458": S("system-sweep", "platform primary-inbox poller (single system account); message_id dedupe against its own inbox rows."),
  "server/heartbeat.ts:2583": S("system-sweep", "global heartbeat scheduler's platform-wide delegation-cap/duplicate check; count + name comparison only."),
  "server/minds-engine.ts:214": S("upstream-verified", "dependsOn is typed number[] (MindTicket contract) so join() yields a numeric literal; tenant_id is a bound param in the same INSERT."),
  "server/minds-engine.ts:262": S("upstream-verified", "typed number[] joined into an ::int[] cast, passed as a bound param, AND the query carries tenant_id = ${tenantId}."),
  "server/routes.ts:3437": S("upstream-verified", "the SELECT fetches the row's tenantId and the very next line returns 403 on mismatch — the query IS the ownership check."),
  "server/surprise-scorer.ts:139": S("internal-worker-pk", "proposalId is threaded from the felix loop's own tenant-scoped proposal row (sibling felix_proposals sites verified in campaign 2026-07-31)."),
  "server/tools/domains/quality/handlers.ts:525": S("upstream-verified", "all interpolations are bound drizzle params (no string concat) and the WHERE includes tenant_id = ${tid} from verified ctx.tenantId."),
  "server/tools/domains/security/handlers.ts:279": S("upstream-verified", "scanSql template params are bound (not concatenated); INSERT includes tenant_id = ${tenantId} from the admin-gated scan handler."),
  "server/video-job-runner.ts:206": S("internal-worker-pk", "isCancelRequested reads by the unguessable random jobId (vj_<base36>_<hex>) generated by the runner itself."),
  "server/skill-seeker.ts:749": D("seekAndLearn defaults tenantId to 1 (admin) in its signature — default-to-admin shape; hardening = require explicit tenantId at all call sites (new deferral, campaign 2026-08-01 pass 2)."),
  "server/storage.ts:959": D("updateHeartbeatTask falls back to an unscoped UPDATE when tenantId omitted — same optional-tenant fail-open family as getMemoryStats/getHeartbeatTasks (new deferral, campaign 2026-08-01 pass 2)."),
};

const latest = JSON.parse(fs.readFileSync(path.join(DIR, "latest.json"), "utf8"));
const severe = (latest.findings as any[]).filter((f) => f.severity === "CRITICAL" || f.severity === "HIGH");

function codeLineFor(file: string, line: number): string | undefined {
  let lines: string[];
  try { lines = fs.readFileSync(file, "utf8").split("\n"); } catch { return undefined; }
  for (const d of [0, 1, -1, 2, -2, 3, -3]) {
    const i = line - 1 + d;
    if (i >= 0 && i < lines.length && isUsableCodeLine(lines[i])) return lines[i].trim();
  }
  return undefined;
}

const newSupp: any[] = [];
const newDefer: any[] = [];
const snapFindings: any[] = [];
const problems: string[] = [];
const covered = new Set<string>();
for (const f of severe) {
  const key = `${f.file}:${f.line}`;
  const d = DISPOSITIONS[key];
  if (!d) continue;
  covered.add(key);
  const anchor = extractStructuralAnchor(f.issue);
  if (!anchor) { problems.push(`NO ANCHOR ${key}`); continue; }
  const match = f.issue.slice(0, 100).trim();
  const codeLine = codeLineFor(f.file, f.line);
  snapFindings.push({ ...f, disposition: d.kind === "defer" ? "deferred" : "allowlisted" });
  if (d.kind === "suppress") newSupp.push({ file: f.file, pattern: d.pattern, match, anchor, reason: d.reason, verifiedBy: VERIFIER, date: TODAY, ...(codeLine ? { codeLine } : {}) });
  else newDefer.push({ file: f.file, match, anchor, reason: d.reason, deferredBy: VERIFIER, date: TODAY, reviewBy: d.reviewBy, ...(codeLine ? { codeLine } : {}) });
}
for (const k of Object.keys(DISPOSITIONS)) if (!covered.has(k)) problems.push(`DISPO UNUSED ${k}`);
console.log(`dispositioned=${snapFindings.length} newSuppressions=${newSupp.length} newDeferrals=${newDefer.length}`);
problems.forEach((p) => console.log(p));
if (WRITE) {
  const supp = JSON.parse(fs.readFileSync(path.join(DIR, "suppressions.json"), "utf8"));
  fs.writeFileSync(path.join(DIR, "suppressions.json"), JSON.stringify([...supp, ...newSupp], null, 2) + "\n");
  const deferPath = path.join(DIR, "deferrals.json");
  const existingDefer = JSON.parse(fs.readFileSync(deferPath, "utf8"));
  fs.writeFileSync(deferPath, JSON.stringify([...existingDefer, ...newDefer], null, 2) + "\n");
  const snapPath = path.join(DIR, `campaign-${TODAY}-snapshot.json`);
  const snap = JSON.parse(fs.readFileSync(snapPath, "utf8"));
  snap.findings = [...snap.findings, ...snapFindings];
  fs.writeFileSync(snapPath, JSON.stringify(snap, null, 2) + "\n");
  console.log("appended to suppressions.json, deferrals.json, campaign snapshot");
} else console.log("dry run — pass --write to persist");
