#!/usr/bin/env tsx
/**
 * scripts/refresh-totals.ts — generates docs/release-facts.json from live
 * registries, then renders docs/CURRENT_PLATFORM_TOTALS.md from those facts.
 *
 * Publication-time evidence sources (maintainer DATABASE_URL required):
 *   tools     → static source-union extraction across legacy + migrated tool definitions
 *   tables-D  → rg -c "= pgTable(" shared/schema.ts (declared)
 *   tables-L  → SELECT count(*) FROM information_schema.tables WHERE table_schema='public'
 *   skills    → SELECT count(*) FROM skills
 *   personas  → SELECT count(*) FROM personas WHERE is_active=true
 *   capabilities → SELECT count(*) FROM capabilities WHERE is_active=true
 *   gov rules → SELECT count(*) FROM governance_rules
 *   indexes   → SELECT count(*) FROM pg_indexes WHERE schemaname='public',
 *                excluding manifest-defined auth/session runtime infrastructure
 *
 * Usage:
 *   npx tsx scripts/refresh-totals.ts          # rewrite docs/CURRENT_PLATFORM_TOTALS.md
 *   npx tsx scripts/refresh-totals.ts --check  # maintainer DB check before publication
 *   npx tsx scripts/refresh-totals.ts --json   # emit numbers as JSON, no file write
 *
 * Env: DATABASE_URL required to regenerate publication evidence.
 *
 * A public checkout verifies committed release facts with verify-counts.ts; it
 * does not reproduce mutable live-database measurements. The release date is
 * a versioned explicit input, never a wall-clock generation timestamp.
 * Safe: read-only against DB and source tree; only mutates generated facts/docs.
 */
import { execSync } from "node:child_process";
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { Pool } from "pg";
import { MODEL_REGISTRY } from "../server/model-registry";
import { extractToolNamesStatic } from "./lib/tool-source-files";

const FACTS_PATH = "docs/release-facts.json";
const FACTS_INPUT_PATH = "docs/release-facts-input.json";
const TOTALS_PATH = "docs/CURRENT_PLATFORM_TOTALS.md";
const INDEX_METRIC_MANIFEST_PATH = "docs/platform-index-metric.json";
const CHECK = process.argv.includes("--check");
const JSON_ONLY = process.argv.includes("--json");

type PlatformIndexMetricManifest = {
  metric: "platform_indexes";
  excludedIndexNames: string[];
};

type ReleaseFacts = {
  schemaVersion: 1;
  releaseDate: string;
  metrics: {
    registeredTools: number;
    publicDocumentedTools: number;
    activePersonas: number;
    dbSeededSkills: number;
    totalSkills: number;
    activeCapabilities: number;
    declaredTables: number;
    liveTables: number;
    governanceRules: number;
    platformIndexes: number;
    nonPrimaryKeyIndexes: number;
    aiProviders: number;
    coreRegistryModels: number;
  };
};

type ReleaseFactsInput = {
  releaseDate: string;
  platformAgentSkills: number;
};

function loadReleaseFactsInput(): ReleaseFactsInput {
  const parsed: unknown = JSON.parse(readFileSync(FACTS_INPUT_PATH, "utf8"));
  const input = parsed as Partial<ReleaseFactsInput>;
  if (
    !input ||
    typeof input.releaseDate !== "string" ||
    !/^\d{4}-\d{2}-\d{2}$/.test(input.releaseDate) ||
    !Number.isSafeInteger(input.platformAgentSkills) ||
    input.platformAgentSkills < 0
  ) {
    throw new Error(`[refresh-totals] invalid ${FACTS_INPUT_PATH}`);
  }
  return input as ReleaseFactsInput;
}

function renderTotals(facts: ReleaseFacts): string {
  const { metrics: c } = facts;
  return `# Current Platform Totals

> **Generated release facts:** [release-facts.json](release-facts.json) is the
> machine-readable source for the current release. This page is a generated
> human-readable rendering; public metadata and count checks consume the same
> facts. Do not hand-edit either generated output.
>
> **Tool-count semantics:** **${c.registeredTools} total registered tools** is the
> complete governed registry. **${c.publicDocumentedTools} public documented tools**
> is the filtered public index and intentionally excludes trusted-persona-only
> tools. These are different valid metrics, not competing totals.

**Release evidence date:** ${facts.releaseDate}. Database-derived values are a
publication-time evidence snapshot generated by \`scripts/refresh-totals.ts\`
with maintainer database access; they are not reproducible from a fresh public
checkout. Fresh checkouts verify committed facts with \`verify-counts.ts\`.

---

## Current Release Facts

| Metric | Value | How it's verified |
|---|---|---|
| **Tools (total registered)** | **${c.registeredTools}** | Static unique-name extraction across \`server/tools.ts\` + migrated domain definitions |
| **Tools (public documented)** | **${c.publicDocumentedTools}** | Registered tools excluding \`trustedPersonasOnly\` policy entries |
| **AI agent personas (active)** | **${c.activePersonas}** | \`SELECT count(*) FROM personas WHERE is_active=true\` |
| **Skills (DB seeded)** | **${c.dbSeededSkills}** | \`SELECT count(*) FROM skills\` |
| **Skills (total incl. .agents/skills/)** | **${c.totalSkills}** | DB count + 4 platform agent skills not yet seeded |
| **Capabilities (active)** | **${c.activeCapabilities}** | \`SELECT count(*) FROM capabilities WHERE is_active=true\` |
| **Database tables (declared)** | **${c.declaredTables}** | \`rg -c "= pgTable("\` in \`shared/schema.ts\` |
| **Database tables (live in \`public\` schema)** | **${c.liveTables}** | \`SELECT count(*) FROM information_schema.tables WHERE table_schema='public'\` |
| **Governance rules** | **${c.governanceRules}** | \`SELECT count(*) FROM governance_rules\` |
| **Platform indexes (release aggregate)** | **${c.platformIndexes}** | Live \`pg_indexes\` count minus versioned auth/session infrastructure exclusions |
| **Production indexes (non-PK operational probe)** | **${c.nonPrimaryKeyIndexes}** | \`SELECT count(*) FROM pg_indexes WHERE schemaname='public' AND indexname NOT LIKE '%_pkey'\` |
| **AI providers** | **${c.aiProviders}** | OpenAI, Anthropic, Google, xAI, OpenRouter, Perplexity |
| **AI models (core registry)** | **${c.coreRegistryModels} curated** | \`MODEL_REGISTRY.length\` in \`server/model-registry.ts\` |

---

## Regeneration

Maintainers run \`npx tsx scripts/refresh-totals.ts\` after a release that changes
a measured registry or database count, with the production evidence database
available. Update the explicit release input before publication. Public
checkouts validate committed facts with \`npx tsx scripts/verify-counts.ts\`;
they do not require database access to reproduce this snapshot.
`;
}

function loadPlatformIndexMetricManifest(): PlatformIndexMetricManifest {
  const parsed: unknown = JSON.parse(readFileSync(INDEX_METRIC_MANIFEST_PATH, "utf8"));
  if (
    !parsed ||
    typeof parsed !== "object" ||
    (parsed as { metric?: unknown }).metric !== "platform_indexes" ||
    !Array.isArray((parsed as { excludedIndexNames?: unknown }).excludedIndexNames) ||
    !(parsed as { excludedIndexNames: unknown[] }).excludedIndexNames.every(
      (name) => typeof name === "string" && name.length > 0,
    )
  ) {
    throw new Error(`[refresh-totals] invalid ${INDEX_METRIC_MANIFEST_PATH}`);
  }
  return parsed as PlatformIndexMetricManifest;
}

function sh(cmd: string): string {
  return execSync(cmd, { encoding: "utf8" }).trim();
}

async function main() {
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) {
    console.error("[refresh-totals] DATABASE_URL not set — cannot query live counts");
    process.exit(2);
  }

  const extractedTools = extractToolNamesStatic();
  if (extractedTools.duplicates.length > 0) {
    throw new Error(
      `[refresh-totals] duplicate tool definitions in the static source union: ${extractedTools.duplicates.join(", ")}`,
    );
  }
  const tools = extractedTools.names.length;
  const tablesDeclared = parseInt(sh(`rg -c "= pgTable\\(" shared/schema.ts`), 10);
  const models = MODEL_REGISTRY.length;
  const indexMetric = loadPlatformIndexMetricManifest();
  const releaseInput = loadReleaseFactsInput();

  const pool = new Pool({ connectionString: databaseUrl });
  try {
    const [tablesLive, skills, personas, capabilities, gov, platformIndexes, excludedIndexes, nonPrimaryKeyIndexes] = await Promise.all([
      pool.query("SELECT count(*)::int AS n FROM information_schema.tables WHERE table_schema='public'"),
      pool.query("SELECT count(*)::int AS n FROM skills"),
      pool.query("SELECT count(*)::int AS n FROM personas WHERE is_active=true"),
      pool.query("SELECT count(*)::int AS n FROM capabilities WHERE is_active=true"),
      pool.query("SELECT count(*)::int AS n FROM governance_rules"),
      pool.query(
        "SELECT count(*)::int AS n FROM pg_indexes WHERE schemaname='public' AND NOT (indexname = ANY($1::text[]))",
        [indexMetric.excludedIndexNames],
      ),
      pool.query(
        "SELECT count(*)::int AS n FROM pg_indexes WHERE schemaname='public' AND indexname = ANY($1::text[])",
        [indexMetric.excludedIndexNames],
      ),
      pool.query("SELECT count(*)::int AS n FROM pg_indexes WHERE schemaname='public' AND indexname NOT LIKE '%_pkey'"),
    ]);
    if (excludedIndexes.rows[0].n !== indexMetric.excludedIndexNames.length) {
      throw new Error(
        `[refresh-totals] expected ${indexMetric.excludedIndexNames.length} manifest-defined infrastructure indexes, found ${excludedIndexes.rows[0].n}`,
      );
    }

    const trustedPolicyNames = new Set(
      [...readFileSync("server/safety/destructive-tool-policy.ts", "utf8")
        .matchAll(/name:\s*"([a-z0-9_]+)"[^\n}]*trustedPersonasOnly:\s*true/g)]
        .map((match) => match[1]),
    );
    const facts: ReleaseFacts = {
      schemaVersion: 1,
      releaseDate: releaseInput.releaseDate,
      metrics: {
        registeredTools: tools,
        publicDocumentedTools: extractedTools.names.filter((name) => !trustedPolicyNames.has(name)).length,
        activePersonas: personas.rows[0].n,
        dbSeededSkills: skills.rows[0].n,
        totalSkills: skills.rows[0].n + releaseInput.platformAgentSkills,
        activeCapabilities: capabilities.rows[0].n,
        declaredTables: tablesDeclared,
        liveTables: tablesLive.rows[0].n,
        governanceRules: gov.rows[0].n,
        platformIndexes: platformIndexes.rows[0].n,
        nonPrimaryKeyIndexes: nonPrimaryKeyIndexes.rows[0].n,
        aiProviders: 6,
        coreRegistryModels: models,
      },
    };

    if (JSON_ONLY) {
      console.log(JSON.stringify(facts, null, 2));
      return;
    }

    const factsJson = `${JSON.stringify(facts, null, 2)}\n`;
    const next = renderTotals(facts);

    if (CHECK) {
      const currentFacts = existsSync(FACTS_PATH) ? readFileSync(FACTS_PATH, "utf8") : "";
      const cur = existsSync(TOTALS_PATH) ? readFileSync(TOTALS_PATH, "utf8") : "";
      if (currentFacts !== factsJson || cur !== next) {
        console.error(`[refresh-totals] generated release facts are STALE — run without --check to regenerate`);
        process.exit(1);
      }
      console.log(`[refresh-totals] ${FACTS_PATH} and ${TOTALS_PATH} are current`);
      return;
    }

    writeFileSync(FACTS_PATH, factsJson);
    writeFileSync(TOTALS_PATH, next);
    console.log(`[refresh-totals] OK — ${FACTS_PATH} and ${TOTALS_PATH} regenerated`);
    console.log(`  registeredTools=${facts.metrics.registeredTools} publicDocumentedTools=${facts.metrics.publicDocumentedTools} skills=${facts.metrics.dbSeededSkills}(+4=${facts.metrics.totalSkills}) personas=${facts.metrics.activePersonas} capabilities=${facts.metrics.activeCapabilities} tables=${facts.metrics.declaredTables}(declared)/${facts.metrics.liveTables}(live) gov=${facts.metrics.governanceRules} indexes=${facts.metrics.platformIndexes}(release)/${facts.metrics.nonPrimaryKeyIndexes}(non-PK)`);
  } finally {
    await pool.end();
  }
}

main().catch(err => {
  console.error("[refresh-totals] FAILED:", err?.message || err);
  process.exit(3);
});
