#!/usr/bin/env tsx
/**
 * scripts/refresh-reviewer-guide.ts — regenerates docs/FOR-EXTERNAL-REVIEWERS.md
 * from the live source tree so external reviews (human or AI) are grounded in
 * current facts, not stale snapshots.
 *
 * Why this exists: an external AI review (2026-07-18) graded a months-old
 * mirror snapshot — flagged tools.ts at 20k+ lines (it was ~9.7k), claimed the
 * project uses Postgres RLS (it deliberately does not), and cited a stale
 * typecheck status. This doc pins the claims reviewers most often get wrong,
 * and is REGENERATED at every mirror build so it cannot drift.
 *
 * Counts (tools/tables/skills/etc.) deliberately live in ONE place —
 * docs/CURRENT_PLATFORM_TOTALS.md (refresh-totals.ts). This guide links there
 * and only carries facts that doc does not: code-shape metrics, architecture
 * intent, and refactor progress.
 *
 * Usage:
 *   npx tsx scripts/refresh-reviewer-guide.ts          # rewrite the doc
 *   npx tsx scripts/refresh-reviewer-guide.ts --check  # exit 1 if doc would change
 *
 * No DB, no network. Read-only except the target doc. Exit 0 ok, 1 check-dirty,
 * 2 hard failure (missing source files).
 */
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const DOC_PATH = "docs/FOR-EXTERNAL-REVIEWERS.md";
const CHECK = process.argv.includes("--check");

function sh(cmd: string): string {
  return execSync(cmd, { encoding: "utf8" }).trim();
}

function lineCount(path: string): number {
  if (!existsSync(path)) {
    console.error(`[reviewer-guide] missing expected file: ${path}`);
    process.exit(2);
  }
  return readFileSync(path, "utf8").split("\n").length;
}

function main() {
  const toolsLines = lineCount("server/tools.ts");
  const routesLines = lineCount("server/routes.ts");

  const pkg = JSON.parse(readFileSync("package.json", "utf8"));
  const deps = Object.keys(pkg.dependencies || {}).length;
  const devDeps = Object.keys(pkg.devDependencies || {}).length;

  // Domains are DIRECTORIES under server/tools/domains/ (one per domain),
  // each holding that domain's .ts modules. Count both grains.
  let domainDirs = 0;
  let domainFiles = 0;
  try {
    domainDirs = parseInt(sh(`find server/tools/domains -mindepth 1 -maxdepth 1 -type d | wc -l`), 10) || 0;
    domainFiles = parseInt(sh(`find server/tools/domains -name '*.ts' -type f | wc -l`), 10) || 0;
  } catch {
    domainDirs = 0;
    domainFiles = 0;
  }
  if (existsSync("server/tools/domains") && (domainDirs === 0 || domainFiles === 0)) {
    console.error("[reviewer-guide] sanity check failed: server/tools/domains exists but counted 0 domains/modules — refusing to publish a false claim");
    process.exit(2);
  }
  let routeModules = 0;
  try {
    routeModules = parseInt(sh(`ls server/routes/*.ts 2>/dev/null | wc -l`), 10) || 0;
  } catch {
    routeModules = 0;
  }

  // Typecheck status — best-effort (skippable via env for fast local runs).
  let typecheck = "not verified in this snapshot — run `npm run check` to confirm";
  if (process.env.SKIP_TSC !== "1") {
    try {
      execSync("npx --no-install tsc --noEmit", { encoding: "utf8", stdio: "pipe" });
      typecheck = "0 errors (`tsc --noEmit` clean at snapshot time)";
    } catch (e: any) {
      const out = String(e?.stdout || "");
      const n = (out.match(/error TS\d+/g) || []).length;
      typecheck = `${n} error(s) at snapshot time (\`tsc --noEmit\`)`;
    }
  }

  const date = new Date().toISOString().slice(0, 10);

  const next = `<!-- AUTO-GENERATED by scripts/refresh-reviewer-guide.ts at every mirror build.
     Do NOT hand-edit — changes will be overwritten. -->
# For External Reviewers

> **Read this before reviewing.** This document is regenerated from the live
> source tree at every public-mirror build (last regenerated **${date}**), so
> the facts below are current for THIS snapshot. Reviews that cite older
> snapshots or third-party summaries of this repo will contain stale findings.

## 1. Where the authoritative numbers live

All platform counts (tools, tables, skills, personas, indexes, governance
rules) live in **one** place: [\`docs/CURRENT_PLATFORM_TOTALS.md\`](CURRENT_PLATFORM_TOTALS.md),
regenerated from live registries at every build. If a number elsewhere in the
repo disagrees with that doc, the totals doc wins — flag the discrepancy, but
grade against the totals doc.

## 2. Facts as of this snapshot (auto-computed)

| Claim reviewers often get wrong | Current reality (${date}) |
| :--- | :--- |
| "\`server/tools.ts\` is a 20,000+ line monolith" | **${toolsLines.toLocaleString()} lines.** An active strangler-fig split is migrating tools into \`server/tools/domains/\` (**${domainDirs} domain packages, ${domainFiles} modules** so far). The 20k figure is historical. |
| "\`server/routes.ts\` is monolithic" | **${routesLines.toLocaleString()} lines**, with **${routeModules} extracted route modules** in \`server/routes/\`. Extraction is ongoing by design (strangler-fig, one domain per session, revert-don't-limp). |
| "Typecheck is failing / burning down" | ${typecheck}. |
| "100+ direct dependencies" | **${deps} runtime dependencies** (+ ${devDeps} dev-only). Audited weekly (dependency audit + SAST + transitive CVE check). |

## 3. Architecture decisions that are DELIBERATE (not gaps)

Please do not report these as findings — they are documented design choices:

- **Tenant isolation is app-level, not Postgres RLS.** Every one of the
  tenant-scoped tables enforces \`tenant_id\` via mandatory WHERE clauses at
  the application layer, verified by a nightly tenant-isolation audit and
  regression tests. The project does **not** use Row-Level Security; any
  review claiming it does is hallucinating a control we never claimed.
  Rationale and threat coverage: see the threat model / security docs.
- **No distributed task queue (Redis/BullMQ/Kafka) — by design.** The platform
  deploys as a single VM. Durability comes from DB-backed scheduled tasks,
  checkpoint/resume pipelines (repair-don't-re-run), and atomic budget-claim
  compare-and-swap before any autonomous spend. Adding queue infrastructure
  would add attack surface without a horizontal-scaling need.
- **Fail-open vs fail-closed is intentional per layer:** safety-critical
  gates (destructive-tool policy) fail **closed**; quality/advisory layers
  (intent-gate classifier, telemetry) fail **open** with loud logging. A
  fail-open branch in an advisory layer is not a bug.
- **Large-file alarm is already in place:** a CI "file-girth" gate fails the
  build if any file exceeds its ceiling, and ceilings only ratchet **down** —
  the historical monolith cannot silently regrow.

## 4. What this mirror is (and is not)

- This is a **sanitized mirror** of a private production repo. Secrets,
  customer SKUs, and some proprietary modules are stubbed or scrubbed at
  build time; a fail-closed leak gate verifies every push.
- Stubbed modules can make some code paths look dead or unwired **in the
  mirror** that are live in production. Before reporting "dead/unwired code,"
  check whether the file header marks it as a mirror stub.
- The mirror lags the private repo by hours-to-days. The regeneration date at
  the top of this doc is the freshness bound for every claim in it.

## 5. How to produce a review we can act on

1. Grade against **this snapshot** (clone at HEAD), not cached summaries.
2. Cite file + line for every finding so it can be verified upstream.
3. Check §3 before flagging an architecture decision as a gap.
4. Reproduce the green suite: \`npm install && bash tests/run.sh\` (see
   \`FORK-SETUP.md\`); the CI badge on the README runs the same suite.

Findings that survive those four steps are genuinely valuable — please open
an issue.
`;

  const current = existsSync(DOC_PATH) ? readFileSync(DOC_PATH, "utf8") : "";
  // Ignore the volatile date when checking so --check doesn't churn daily.
  const normalize = (s: string) => s.replace(/\d{4}-\d{2}-\d{2}/g, "DATE");
  if (CHECK) {
    if (normalize(current) !== normalize(next)) {
      console.error("[reviewer-guide] docs/FOR-EXTERNAL-REVIEWERS.md is stale");
      process.exit(1);
    }
    console.log("[reviewer-guide] up to date");
    return;
  }
  writeFileSync(DOC_PATH, next);
  console.log(`[reviewer-guide] wrote ${DOC_PATH} (tools.ts=${toolsLines}, routes.ts=${routesLines}, deps=${deps})`);
}

main();
