#!/usr/bin/env tsx
/**
 * Fail-closed guard: the public mirror's docs/tools.md must list exactly the
 * platform's public tool surface. docs/tools.md is regenerated by
 * scripts/generate-public-docs.ts via REGEX over server/tools.ts +
 * server/tools/domains/** — a new tool-definition file/shape the extractor
 * doesn't cover silently drops tools from the mirror (same failure mode as
 * the Task #83 persona incident, guarded at stage 0.1).
 *
 * Authoritative surface: server/tool-registry.ts (getAllRegisteredTools —
 * imports cleanly, does NOT pull the tools.ts app graph) minus tools flagged
 * trustedPersonasOnly in TOOL_POLICIES (intentionally excluded from the
 * public index). Compares NAME SETS, not just counts, so an add+drop pair
 * that nets to zero is still caught.
 *
 * Exit codes: 0 = doc matches authoritative surface; 1 = mismatch OR doc
 * unreadable/internally inconsistent (fail closed).
 */
import * as fs from "fs";
import * as path from "path";
import { getAllRegisteredTools } from "../server/tool-registry";
import { TOOL_POLICIES } from "../server/safety/destructive-tool-policy";
import { checkToolsDoc } from "./lib/mirror-doc-guards";

function main(): number {
  const docPath = path.join(process.cwd(), "docs/tools.md");
  if (!fs.existsSync(docPath)) {
    console.error(`✗ tool-count guard: ${docPath} missing — run scripts/generate-public-docs.ts first`);
    return 1;
  }
  const doc = fs.readFileSync(docPath, "utf8");

  // Authoritative public surface: metadata registry minus trusted-only tools.
  let registered: string[];
  let trustedOnly: string[];
  try {
    registered = getAllRegisteredTools();
    trustedOnly = Object.values(TOOL_POLICIES)
      .filter((p) => p.trustedPersonasOnly)
      .map((p) => p.name);
  } catch (err) {
    console.error(`✗ tool-count guard: failed to load authoritative tool surface — ${(err as Error).message} (fail closed)`);
    return 1;
  }

  const result = checkToolsDoc(doc, registered, trustedOnly);
  if (!result.ok) {
    console.error(`✗ tool-count guard: ${result.message}`);
    return 1;
  }
  console.log(`✓ tool-count guard: ${result.message}`);
  return 0;
}

process.exit(main());
