/**
 * Weekly wedge progress digest — Mondays 08:00 local.
 *
 * For each active wedge track, queries:
 *   - waitlist signups (last 7d vs prior 7d)
 *   - paid conversions (Stripe events table if present)
 *   - content shipped (Felix deliverables tagged with the wedge)
 *   - any S/A-tier IOTDs scored in the last 7d
 *   - top action surfaced by the agent
 *
 * Output: writes a markdown digest to docs/wedge-digest-YYYY-MM-DD.md, uploads
 * to the active "Bob's Replit Ideabrowser" project Drive folder, AND sends an
 * owner-notification email so Bob sees it in his inbox Monday morning.
 *
 * Designed for Replit Scheduled Deployment (weekly, Mon 08:00 America/New_York).
 * Idempotent on the date — re-running on the same Monday updates the same file.
 */
import { db } from "../server/db";
import { sql } from "drizzle-orm";
import { storage } from "../server/storage";
import { ensureProjectFolder, uploadAndShare } from "../server/google-drive";
import * as fs from "fs";
import * as path from "path";

const TENANT_ID = 1;
const PROJECT_NAME = "Bob's Replit Ideabrowser";

// Wedge tracks are discovered dynamically from projects tagged 'wedge' (slug
// from the wedge:* tag, source from the track:* tag) so new wedges appear in
// the digest automatically — the old hardcoded 3-track list silently omitted
// Archive Rescue, Creator Sponsor Ops, and every later wedge (Bob 2026-08-08).
async function discoverTracks(): Promise<{ slug: string; name: string; source: string }[]> {
  const res: any = await db.execute(sql`
    SELECT name, tags FROM projects
    WHERE tenant_id=${TENANT_ID} AND 'wedge' = ANY(tags)
    ORDER BY id
  `);
  return (res.rows || res).map((r: any) => {
    const tags: string[] = Array.isArray(r.tags) ? r.tags : [];
    const slug = (tags.find((t) => t.startsWith("wedge:")) || "wedge:unknown").slice("wedge:".length);
    const source = (tags.find((t) => t.startsWith("track:")) || "track:untracked").slice("track:".length);
    return { slug, name: r.name.replace(/^Wedge:\s*/, ""), source };
  });
}

// Fail-CLOSED (architect 2026-08-09): a DB error must surface as "data
// unavailable", never as a fake 0 — a zero drives false "zero traction"
// recommendations. Returns null on failure; callers must branch on it.
async function safeCount(q: any): Promise<number | null> {
  try {
    const r: any = await db.execute(q);
    return Number((r.rows || r)[0]?.n || 0);
  } catch (e: any) {
    console.error(`[digest] metric query failed — reporting data-unavailable, not 0: ${e?.message || e}`);
    return null;
  }
}

(async () => {
  const today = new Date().toISOString().slice(0, 10);
  console.log(`[digest] generating wedge digest for ${today}`);

  const TRACKS = await discoverTracks();
  console.log(`[digest] discovered ${TRACKS.length} wedge track(s): ${TRACKS.map((t) => t.slug).join(", ")}`);

  let md = `# Weekly Wedge Digest — ${today}\n\n`;
  md += `Autogenerated by \`scripts/weekly-wedge-digest.ts\` for all ${TRACKS.length} active wedges (auto-discovered).\n\n`;
  md += `## Headline\n\n`;

  const trackSummaries: { name: string; signups7d: number; signupsPrev: number; conversions: number; contentShipped: number }[] = [];
  let metricsDegraded = false; // any track with a failed metric query ⇒ no aggregate trend claims

  for (const t of TRACKS) {
    md += `\n## ${t.name} _(${t.source})_\n\n`;
    // Lead source of truth is audit_leads (there is NO 'leads' table — the old
    // query silently returned 0 forever via the catch). Wedge attribution via
    // UTM/notes slug match; the audit wedge owns the whole storefront funnel.
    const leadFilter = t.slug === "audit-pro"
      ? sql`TRUE`
      : sql`(utm_campaign ILIKE '%' || ${t.slug}::text || '%' OR utm_content ILIKE '%' || ${t.slug}::text || '%' OR utm_source ILIKE '%' || ${t.slug}::text || '%' OR notes ILIKE '%' || ${t.slug}::text || '%')`;
    const signups7d = await safeCount(sql`
      SELECT COUNT(*)::int AS n FROM audit_leads
      WHERE tenant_id=${TENANT_ID}
        AND ${leadFilter}
        AND created_at > NOW() - INTERVAL '7 days'
    `);
    const signupsPrev = await safeCount(sql`
      SELECT COUNT(*)::int AS n FROM audit_leads
      WHERE tenant_id=${TENANT_ID}
        AND ${leadFilter}
        AND created_at > NOW() - INTERVAL '14 days'
        AND created_at <= NOW() - INTERVAL '7 days'
    `);
    const contentShipped = await safeCount(sql`
      SELECT COUNT(*)::int AS n FROM project_files pf
      JOIN projects p ON p.id = pf.project_id
      WHERE p.tenant_id=${TENANT_ID}
        AND ('wedge:' || ${t.slug}::text) = ANY(p.tags)
        AND pf.created_at > NOW() - INTERVAL '7 days'
    `);

    // Fail-closed: any unavailable metric ⇒ report "n/a" and skip trend
    // recommendations for this track (never advise off fake zeros).
    if (signups7d === null || signupsPrev === null || contentShipped === null) {
      md += `| Metric | This week | Prior week | Δ |\n|---|---:|---:|---:|\n`;
      md += `| Waitlist signups | ${signups7d ?? "n/a"} | ${signupsPrev ?? "n/a"} | n/a |\n`;
      md += `| Content shipped | ${contentShipped ?? "n/a"} | — | — |\n\n`;
      md += `**Recommendation:** ⚠️ Metrics unavailable this week (DB query failed) — no trend call made. Investigate the digest logs before acting.\n\n`;
      metricsDegraded = true;
      continue;
    }

    const delta = signups7d - signupsPrev;
    const deltaStr = delta > 0 ? `+${delta}` : `${delta}`;
    md += `| Metric | This week | Prior week | Δ |\n|---|---:|---:|---:|\n`;
    md += `| Waitlist signups | ${signups7d} | ${signupsPrev} | ${deltaStr} |\n`;
    md += `| Content shipped | ${contentShipped} | — | — |\n\n`;

    // Recommendation per track based on signal
    if (signups7d === 0 && signupsPrev === 0) {
      md += `**Recommendation:** Zero traction. Ship at least 1 piece of content this week to drive funnel attention.\n\n`;
    } else if (signups7d >= 5) {
      md += `**Recommendation:** Strong signal (${signups7d} signups). Run a manual concierge call with the top-3 most-recent leads.\n\n`;
    } else if (delta < -2) {
      md += `**Recommendation:** Declining trend (${deltaStr} WoW). Funnel attention is dropping — diagnose: stale content? channel saturation? Refresh.\n\n`;
    } else {
      md += `**Recommendation:** Holding pattern. Ship 1–2 more content pieces this week; reassess next Monday.\n\n`;
    }

    trackSummaries.push({ name: t.name, signups7d, signupsPrev, conversions: 0, contentShipped });
  }

  // New S/A tier IOTDs surfaced this week
  const freshSA: any = await db.execute(sql`
    SELECT name, metadata->'priority'->>'tier' AS tier,
           (metadata->'priority'->>'composite')::int AS composite,
           metadata->'priority'->>'buyer_hypothesis' AS buyer
    FROM projects
    WHERE tenant_id = ${TENANT_ID}
      AND metadata ? 'priority'
      AND metadata->'priority'->>'tier' IN ('S','A')
      AND (
        (metadata->'priority'->>'scored_at')::timestamptz > NOW() - INTERVAL '7 days'
        OR (created_at > NOW() - INTERVAL '7 days' AND metadata ? 'priority')
      )
    ORDER BY composite DESC
    LIMIT 10
  `);
  const fresh = (freshSA.rows || freshSA);
  md += `\n## New S/A-tier ideas surfaced this week (${fresh.length})\n\n`;
  if (fresh.length === 0) {
    md += `None.\n\n`;
  } else {
    fresh.forEach((f: any, i: number) => {
      md += `${i + 1}. **[${f.tier} ${f.composite}]** ${f.name} — ${f.buyer || "buyer TBD"}\n`;
    });
    md += `\n`;
  }

  // Headline summary (now that we have data)
  const totalSignups = trackSummaries.reduce((a, b) => a + b.signups7d, 0);
  const totalContent = trackSummaries.reduce((a, b) => a + b.contentShipped, 0);
  let headline: string;
  if (metricsDegraded) {
    // Fail-closed: incomplete data ⇒ no "zero motion"/trend claims off partial sums.
    headline = `⚠️ **Metrics incomplete this week** — one or more wedge queries failed; totals below cover only the tracks with data (signups: ${totalSignups}, content: ${totalContent}, new S/A IOTDs: ${fresh.length}). No portfolio trend call made; check digest logs.\n`;
    md = md.replace("## Headline\n\n", `## Headline\n\n${headline}\n`);
  } else {
  headline = `**Total waitlist signups this week: ${totalSignups}** · **Content pieces shipped: ${totalContent}** · **New S/A IOTDs: ${fresh.length}**\n\n`;
  if (totalSignups === 0 && totalContent === 0) {
    headline += `🚨 Zero motion across all ${TRACKS.length} wedges this week. Highest-leverage move: ship the BWB "I built X" video for the highest-signup wedge.\n`;
  } else if (totalSignups >= 10) {
    headline += `🟢 Strong week. ≥10 signups across the portfolio. Time to qualify the warmest leads into paying customers.\n`;
  } else {
    headline += `🟡 Modest motion. Stay the course; reassess in 14 days for trend confirmation.\n`;
  }
  md = md.replace("## Headline\n\n", `## Headline\n\n${headline}\n`);
  }

  // Write file
  const outPath = `docs/wedge-digest-${today}.md`;
  fs.writeFileSync(outPath, md, "utf-8");
  console.log(`[digest] wrote ${outPath} (${md.length} chars)`);

  // Upload to Bob's Replit Ideabrowser project
  try {
    const projRes: any = await db.execute(sql`
      SELECT id, drive_folder_id FROM projects
      WHERE tenant_id=${TENANT_ID} AND name=${PROJECT_NAME} LIMIT 1
    `);
    const proj = (projRes.rows || projRes)[0];
    if (proj?.drive_folder_id) {
      const tenant = await storage.getTenant(TENANT_ID);
      const tenantName = tenant?.name || `tenant-${TENANT_ID}`;
      await ensureProjectFolder(proj.id, PROJECT_NAME, TENANT_ID, tenantName);
      const up = await uploadAndShare({
        filePath: outPath,
        fileName: path.basename(outPath),
        mimeType: "text/markdown",
        folderLabel: `Projects/${PROJECT_NAME}`,
        description: `Weekly wedge digest ${today}`,
        parentFolderId: proj.drive_folder_id,
        share: true,
      });
      console.log(`[digest] uploaded: ${up.viewUrl}`);
    } else {
      console.log(`[digest] project not found or no drive folder — skip upload`);
    }
  } catch (e: any) {
    console.warn(`[digest] upload failed: ${e.message}`);
  }

  process.exit(0);
})().catch((e) => {
  console.error("[FATAL]", e);
  process.exit(1);
});
